x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://browse.virgon.mindful-web.parameter1.com/graphql}
  CSS_MODE: ${CSS_MODE-optimized}
  DEBUG: ${DEBUG-mail}
  ENABLE_CONTENT_METER: ${ENABLE_CONTENT_METER-false}
  GTM_CONTAINER_ID: ${GTM_CONTAINER_ID}
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://apis.mindfulcms.com/graphql/idx-compat}
  IDX_NAV_ENABLE: ${IDX_NAV_ENABLE-false}
  MINDFUL_EMAIL_API_KEY: ${MINDFUL_EMAIL_API_KEY}
  MINDFUL_EMAIL_ENDPOINT: ${MINDFUL_EMAIL_ENDPOINT}
  NATIVEX_SERVE_URI: ${NATIVEX_SERVE_URI-}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-}
  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-}
  SUGGESTED_VIDEO_ID: ${SUGGESTED_VIDEO_ID-},
  SUGGESTED_VIDEO_PLAYLIST: ${SUGGESTED_VIDEO_PLAYLIST-}
  USE_LINK_INJECTED_BODY: ${USE_LINK_INJECTED_BODY-false}
  YARN_CACHE_FOLDER: /.yarn-cache

x-site-command: &site-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  de:
    <<: *site-cmd
    working_dir: /root/sites/diverseeducation.com
    environment:
      <<: *env
      HOST: www-cma-de.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9810
      LIVERELOAD_PORT: 19810
    hostname: www-cma-de.dev.parameter1.com
    ports:
      - "9810:80"
      - "19810:19810"

  ccn:
    <<: *site-cmd
    working_dir: /root/sites/ccnewsnow.com
    environment:
      <<: *env
      HOST: www-cma-ccn.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9813
      LIVERELOAD_PORT: 19813
    hostname: www-cma-ccn.dev.parameter1.com
    ports:
      - "9813:80"
      - "19813:19813"
