module.exports = [
  {
    institution: 'Holy Names University',
    officer: 'Laura Lyndon, Ed.D.',
    location: 'Oakland, CA',
    control: 'private',
    fullTime: 20,
    partTime: 14,
    female: 'NO',
    ethnic: 'NO',
    lgbt: 'YES',
    diability: 'NO',
    senior: 98000,
    mid: 70000,
    entry: 58000,
    caregivingLeaveForAll: 'YES',
    childServices: 'NO',
    continueEd: 'YES',
    edLeave: 'NO',
    elderCare: 'YES',
    flexCare: 'NO',
    avgSalarMid: 'YES',
    stressReduction: 'YES',
  },
  {
    institution: 'Fontbonne University',
    officer: 'Heather French, Ed.D.',
    location: 'St. Louis, MO',
    control: 'private',
    fullTime: 14,
    partTime: 7,
    female: 'YES',
    ethnic: 'YES',
    lgbt: 'YES',
    diability: 'NnrR',
    senior: 75000,
    mid: 52000,
    entry: 37000,
    caregivingLeaveForAll: 'YES',
    childServices: 'NO',
    continueEd: 'NO',
    edLeave: 'YES',
    elderCare: 'NO',
    flexCare: 'YES',
    avgSalarMid: 'NO',
    stressReduction: 'YES',
  },
  {
    institution: 'Colgate University',
    officer: 'Paul J. McLoughlin II, Ph.D.',
    location: 'Hamilton, NY',
    control: 'private',
    fullTime: 114,
    partTime: 25,
    female: 'YES',
    ethnic: 'NO',
    lgbt: 'YES',
    diability: 'YES',
    senior: 137255,
    mid: 76958,
    entry: 51324,
    caregivingLeaveForAll: 'YES',
    childServices: 'NO',
    continueEd: 'YES',
    edLeave: 'YES',
    elderCare: 'NO',
    flexCare: 'YES',
    avgSalarMid: 'YES',
    stressReduction: 'NO',
  },
  {
    institution: 'Case Western Reserve University',
    officer: 'Lou W. Stark',
    location: 'Cleveland, OH',
    control: 'private',
    fullTime: 141,
    partTime: 31,
    female: 'YES',
    ethnic: 'NO',
    lgbt: 'N/R',
    diability: 'NnrR',
    senior: 0,
    mid: 0,
    entry: 0,
    caregivingLeaveForAll: 'NO',
    childServices: 'NO',
    continueEd: 'YES',
    edLeave: 'YES',
    elderCare: 'NO',
    flexCare: 'NO',
    avgSalarMid: 'YES',
    stressReduction: 'YES',
  },
  {
    institution: 'Rider University',
    officer: 'Leanna Fenneberg, Ph.D.',
    location: 'Lawrenceville, NJ',
    control: 'private',
    fullTime: 39,
    partTime: 3,
    female: 'YES',
    ethnic: 'YES',
    lgbt: 'YES',
    diability: 'NnrR',
    senior: 86053,
    mid: 65659,
    entry: 49422,
    caregivingLeaveForAll: 'YES',
    childServices: 'NO',
    continueEd: 'YES',
    edLeave: 'NO',
    elderCare: 'NO',
    flexCare: 'YES',
    avgSalarMid: 'YES',
    stressReduction: 'YES',
  },
  {
    institution: 'The University of Delaware',
    officer: 'Jose-Luis Riera, Ph.D.',
    location: 'Newark, DE',
    control: 'public',
    fullTime: 170,
    partTime: 3,
    female: 'YES',
    ethnic: 'NO',
    lgbt: 'N/R',
    diability: 'NO',
    senior: 119000,
    mid: 70700,
    entry: 58200,
    caregivingLeaveForAll: 'YES',
    childServices: 'YES',
    continueEd: 'YES',
    edLeave: 'YES',
    elderCare: 'NO',
    flexCare: 'YES',
    avgSalarMid: 'YES',
    stressReduction: 'YES',
  },
  {
    institution: 'The University of Maryland, College Park',
    officer: 'Patricia A. Perillo, Ph.D.',
    location: 'College Park, MD',
    control: 'public',
    fullTime: 994,
    partTime: 1210,
    female: 'YES',
    ethnic: 'YES',
    lgbt: 'N/R',
    diability: 'NO',
    senior: 173979,
    mid: 95991,
    entry: 49943,
    caregivingLeaveForAll: 'YES',
    childServices: 'YES',
    continueEd: 'YES',
    edLeave: 'YES',
    elderCare: 'YES',
    flexCare: 'YES',
    avgSalarMid: 'NO',
    stressReduction: 'YES',
  },
  {
    institution: 'Kent State University',
    officer: 'Lamar Hylton, Ph.D.',
    location: 'Kent, OH',
    control: 'public',
    fullTime: 265,
    partTime: 52,
    female: 'YES',
    ethnic: 'NO',
    lgbt: 'N/R',
    diability: 'NnrR',
    senior: 100846,
    mid: 63520,
    entry: 42427,
    caregivingLeaveForAll: 'YES',
    childServices: 'YES',
    continueEd: 'YES',
    edLeave: 'NO',
    elderCare: 'NO',
    flexCare: 'YES',
    avgSalarMid: 'YES',
    stressReduction: 'YES',
  },
  {
    institution: 'The U of North Carolina at Greensboro',
    officer: 'Cathy Akens, Ed.D.',
    location: 'Greensboro, NC',
    control: 'public',
    fullTime: 229,
    partTime: 38,
    female: 'YES',
    ethnic: 'YES',
    lgbt: 'YES',
    diability: 'YES',
    senior: 80000,
    mid: 60000,
    entry: 45000,
    caregivingLeaveForAll: 'YES',
    childServices: 'YES',
    continueEd: 'YES',
    edLeave: 'NO',
    elderCare: 'NO',
    flexCare: 'YES',
    avgSalarMid: 'NO',
    stressReduction: 'YES',
  },
  {
    institution: 'California Poly State U',
    officer: 'Keith Humphrey, Ph.D.',
    location: 'San Luis Obispo, CA',
    control: 'public',
    fullTime: 359,
    partTime: 67,
    female: 'YES',
    ethnic: 'YES',
    lgbt: 'N/R',
    diability: 'NnrR',
    senior: 177084,
    mid: 79262,
    entry: 56159,
    caregivingLeaveForAll: 'YES',
    childServices: 'YES',
    continueEd: 'YES',
    edLeave: 'YES',
    elderCare: 'NO',
    flexCare: 'YES',
    avgSalarMid: 'NO',
    stressReduction: 'YES',
  },
  {
    institution: 'West Chester University of Pennsylvania',
    officer: 'Zebulun Davenport, Ed.D.',
    location: 'Westchester, PA',
    control: 'public',
    fullTime: 142,
    partTime: 35,
    female: 'YES',
    ethnic: 'NO',
    lgbt: 'YES',
    diability: 'NO',
    senior: 112523,
    mid: 71051,
    entry: 50002,
    caregivingLeaveForAll: 'YES',
    childServices: 'YES',
    continueEd: 'YES',
    edLeave: 'YES',
    elderCare: 'YES',
    flexCare: 'YES',
    avgSalarMid: 'YES',
    stressReduction: 'YES',
  },
  {
    institution: 'University of California, Riverside',
    officer: 'Brian L. Haynes, Ph.D.',
    location: 'Riverside, CA',
    control: 'public',
    fullTime: 250,
    partTime: 40,
    female: 'YES',
    ethnic: 'YES',
    lgbt: 'N/R',
    diability: 'NnrR',
    senior: 120202,
    mid: 76496,
    entry: 46296,
    caregivingLeaveForAll: 'YES',
    childServices: 'YES',
    continueEd: 'YES',
    edLeave: 'YES',
    elderCare: 'YES',
    flexCare: 'YES',
    avgSalarMid: 'NO',
    stressReduction: 'YES',
  },
  {
    institution: 'William & Mary',
    officer: 'Virginia M. Ambler, Ph.D.',
    location: 'Williamsburg, VA',
    control: 'public',
    fullTime: 105,
    partTime: 51,
    female: 'YES',
    ethnic: 'NO',
    lgbt: 'YES',
    diability: 'NnrR',
    senior: 132608,
    mid: 83360,
    entry: 51177,
    caregivingLeaveForAll: 'YES',
    childServices: 'YES',
    continueEd: 'YES',
    edLeave: 'NO',
    elderCare: 'YES',
    flexCare: 'YES',
    avgSalarMid: 'YES',
    stressReduction: 'YES',
  },
  {
    institution: 'University of Maryland-Baltimore',
    officer: 'Patty Alvarez, Ph.D.',
    location: 'Baltimore, MD',
    control: 'public',
    fullTime: 58,
    partTime: 133,
    female: 'YES',
    ethnic: 'YES',
    lgbt: 'YES',
    diability: 'YES',
    senior: 100363,
    mid: 75452,
    entry: 61090,
    caregivingLeaveForAll: 'YES',
    childServices: 'YES',
    continueEd: 'YES',
    edLeave: 'NO',
    elderCare: 'YES',
    flexCare: 'YES',
    avgSalarMid: 'YES',
    stressReduction: 'YES',
  },
  {
    institution: 'Stockton University',
    officer: 'Christopher Catching, Ed.D.',
    location: '</td>Galloway, NJ',
    control: 'private',
    fullTime: 81,
    partTime: 215,
    female: 'YES',
    ethnic: 'YES',
    lgbt: 'N/R',
    diability: 'NnrR',
    senior: 105000,
    mid: 85000,
    entry: 60000,
    caregivingLeaveForAll: 'YES',
    childServices: 'NO',
    continueEd: 'YES',
    edLeave: 'NO',
    elderCare: 'NO',
    flexCare: 'NO',
    avgSalarMid: 'NO',
    stressReduction: 'YES',
  },
  {
    institution: 'Elon University',
    officer: 'Jon Dooley, Ph.D.',
    location: 'Elon, NC',
    control: 'private',
    fullTime: 100,
    partTime: 5,
    female: 'YES',
    ethnic: 'YES',
    lgbt: 'N/R',
    diability: 'NnrR',
    senior: 86427,
    mid: 59526,
    entry: 47560,
    caregivingLeaveForAll: 'YES',
    childServices: 'NO',
    continueEd: 'YES',
    edLeave: 'NO',
    elderCare: 'NO',
    flexCare: 'YES',
    avgSalarMid: 'NO',
    stressReduction: 'YES',
  },
];
