module.exports = {
  // Put years after 2020 here
  2020: {
    description: 'Now in its 7th year, Most Promising Places to Work in Student Affairs (MPPWSA) is a national recognition that celebrates student affairs workplaces that are vibrant, diverse, supportive and commited to staff work-life balance, professional development and inclusive excellence. MPPWSA offers intitutional leaders information that can be used to improve practices across their student affairs community, while also serving as a useful tool for employers, career services staff and job-seekers across the country.',
    logosSrc: 'https://img.diverseeducation.com/files/base/diverse/all/image/static/de/mppwsa/2020MPPSCHOOLS.jpeg?w=1600&auto=format,compress&q=70',
    tableLabels: {
      tableOne: {
        officer: 'Senior Student Affairs Officer',
        location: 'Location',
        level: 'Level',
        control: 'Control',
      },
      tableTwo: {
        'full-time': '# Full Time Staff',
        'part-time': '# Part Time Staff',
        female: '50% Female',
        minority: '30% Ethnic Minority',
        lgbt: '5% LGBT Staff',
        disability: '5% Staff with Disabilities',
        'senior-salary': 'Average Salary Senior',
        'mid-salary': 'Average Salary Mid-Level',
        'entry-salary': 'Average Salary Entry-Level',
      },
      tableThree: {
        'caregiving-leave': 'Cargiving Leave For All',
        childcare: 'Childcare Services',
        'continuing-ed': 'Continuing Ed',
        'ed-leave': 'Ed Leave',
        'elder-care': 'Elder Care Services',
        flexible: 'Flexible Work Schedule',
        mentoring: 'Mentoring',
        stress: 'Stree Reduction Program',
      },
      salaryChart: {
        senior: 'Average Salary: Senior-Level Staff',
        mid: 'Average Salary: Mid-Level Staff',
        entry: 'Average Salary: Entry-Level Staff',
      },
    },
    institutionData: {
      'Davidson College': {
        tableOne: {
          officer: 'Dr. Byron P. McCrae',
          location: 'Davidson, NC',
          level: '4-year',
          control: 'private',
        },
        tableTwo: {
          'full-time': '70',
          'part-time': '25',
          female: 'YES',
          minority: 'NO',
          lgbt: 'YES',
          disability: 'NO',
          'senior-salary': '$93,000',
          'mid-salary': '$70,000',
          'entry-salary': '$50,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 93000,
          mid: 70000,
          entry: 50000,
        },
      },
      'University of California-Santa Barbara': {
        tableOne: {
          officer: 'Jill Hurd',
          location: 'Santa Barbara, CA',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '63',
          'part-time': '0',
          female: 'NO',
          minority: 'YES',
          lgbt: 'YES',
          disability: 'YES',
          'senior-salary': '$150,000',
          'mid-salary': '$95,000',
          'entry-salary': '$63,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'NO',
          'ed-leave': 'NO',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 150000,
          mid: 95000,
          entry: 63000,
        },
      },
      'University of West Georgia': {
        tableOne: {
          officer: 'Dr. Xavier Whitaker',
          location: 'Carrollton, GA',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '191',
          'part-time': '767',
          female: 'YES',
          minority: 'YES',
          lgbt: 'YES',
          disability: 'NO',
          'senior-salary': '$120,000',
          'mid-salary': '$58,000',
          'entry-salary': '$38,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'NO',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'YES',
          stress: 'YES',
        },
        salaryChart: {
          senior: 120000,
          mid: 58000,
          entry: 38000,
        },
      },
      'Rochester Institute of Technology': {
        tableOne: {
          officer: 'Dr. Sandra Johnson',
          location: 'Rochester, NY',
          level: '4-year',
          control: 'private',
        },
        tableTwo: {
          'full-time': '257',
          'part-time': '150',
          female: 'YES',
          minority: 'NO',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': '$140,000',
          'mid-salary': '$95,000',
          'entry-salary': '$54,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'NO',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 140000,
          mid: 95000,
          entry: 54000,
        },
      },
      'Samuel Merritt University': {
        tableOne: {
          officer: 'Dr. Terry Nordstrom',
          location: 'Oakland, CA',
          level: '4-year',
          control: 'private',
        },
        tableTwo: {
          'full-time': '47',
          'part-time': '2',
          female: 'NO',
          minority: 'NO',
          lgbt: 'YES',
          disability: 'NO',
          'senior-salary': '$120,000',
          'mid-salary': '$90,000',
          'entry-salary': '$60,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'NO',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 120000,
          mid: 90000,
          entry: 60000,
        },
      },
      'Indiana State University': {
        tableOne: {
          officer: 'Dr. Andy Morgan',
          location: 'Terre Haute, IN',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '150',
          'part-time': '400',
          female: 'YES',
          minority: 'YES',
          lgbt: 'YES',
          disability: 'NO',
          'senior-salary': '$60,000',
          'mid-salary': '$50,000',
          'entry-salary': '$40,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'NO',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 60000,
          mid: 50000,
          entry: 40000,
        },
      },
      'University of Florida': {
        tableOne: {
          officer: 'Dr. Winfred Phillips',
          location: 'Gainesville, FL',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '675',
          'part-time': '1709',
          female: 'YES',
          minority: 'YES',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': 'N/R',
          'mid-salary': 'N/R',
          'entry-salary': 'N/R',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 'N/R',
          mid: 'N/R',
          entry: 'N/R',
        },
      },
      'University of North Carolina-Wilmington': {
        tableOne: {
          officer: 'Patricia Leonard',
          location: 'Wilmington, NC',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '169',
          'part-time': '11',
          female: 'YES',
          minority: 'NO',
          lgbt: 'NO',
          disability: 'NO',
          'senior-salary': '$100,000',
          'mid-salary': '$80,000',
          'entry-salary': '$50,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'NO',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'YES',
          stress: 'YES',
        },
        salaryChart: {
          senior: 100000,
          mid: 80000,
          entry: 50000,
        },
      },
      'Miami University-Oxford': {
        tableOne: {
          officer: 'Dr. Jayne Brownell',
          location: 'Oxford, OH',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '102',
          'part-time': '20',
          female: 'N/R',
          minority: 'N/R',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': '$92,000',
          'mid-salary': '$60,000',
          'entry-salary': '$42,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'YES',
          stress: 'YES',
        },
        salaryChart: {
          senior: 92000,
          mid: 60000,
          entry: 42000,
        },
      },
      'Bowling Green State University': {
        tableOne: {
          officer: 'Dr. Thomas Gibson',
          location: 'Bowling Green, OH',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '90',
          'part-time': '5',
          female: 'N/R',
          minority: 'N/R',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': '$109,000',
          'mid-salary': '$55,000',
          'entry-salary': '$42,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'NO',
          'continuing-ed': 'YES',
          'ed-leave': 'NO',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 109000,
          mid: 55000,
          entry: 42000,
        },
      },
      'Pennsylvania College of Technology': {
        tableOne: {
          officer: 'Dr. Elliot Strickland',
          location: 'Williamsport, PA',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '124',
          'part-time': '279',
          female: 'YES',
          minority: 'NO',
          lgbt: 'NO',
          disability: 'YES',
          'senior-salary': '$89,000',
          'mid-salary': '$63,000',
          'entry-salary': '$52,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 89000,
          mid: 63000,
          entry: 52000,
        },
      },
      'University of Vermont': {
        tableOne: {
          officer: 'Dr. Annie Stevens',
          location: 'Burlington, VT',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '230',
          'part-time': '6',
          female: 'YES',
          minority: 'NO',
          lgbt: 'YES',
          disability: 'YES',
          'senior-salary': '$100,000',
          'mid-salary': '$75,000',
          'entry-salary': '$40,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 100000,
          mid: 75000,
          entry: 40000,
        },
      },
      'Ohio University Athens': {
        tableOne: {
          officer: 'Dr. Jason Pina',
          location: 'Athens, OH',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '360',
          'part-time': '12',
          female: 'N/R',
          minority: 'N/R',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': '$107,000',
          'mid-salary': '$73,000',
          'entry-salary': '$46,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'YES',
          stress: 'YES',
        },
        salaryChart: {
          senior: 107000,
          mid: 73000,
          entry: 46000,
        },
      },
      'The State U. of New York-College at Geneseo': {
        tableOne: {
          officer: 'Dr. David G. Braverman',
          location: 'Geneseo, NY',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '125',
          'part-time': '5',
          female: 'YES',
          minority: 'YES',
          lgbt: 'YES',
          disability: 'YES',
          'senior-salary': '$75,000',
          'mid-salary': '$55,000',
          'entry-salary': '$45,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'NO',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'YES',
          stress: 'YES',
        },
        salaryChart: {
          senior: 75000,
          mid: 55000,
          entry: 45000,
        },
      },
      'Rutgers University-New Brunswick': {
        tableOne: {
          officer: 'Dr. Salvador Mena',
          location: 'New Brunswick, NJ',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '1200',
          'part-time': '80',
          female: 'YES',
          minority: 'YES',
          lgbt: 'YES',
          disability: 'YES',
          'senior-salary': '$130,000',
          'mid-salary': '$85,000',
          'entry-salary': '$60,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 130000,
          mid: 85000,
          entry: 60000,
        },
      },
      'College of William & Mary': {
        tableOne: {
          officer: 'Dr. Virginia Ambler',
          location: 'Williamsburg, VA',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '119',
          'part-time': '31',
          female: 'YES',
          minority: 'NO',
          lgbt: 'NO',
          disability: 'N/R',
          'senior-salary': '$121,000',
          'mid-salary': '$64,000',
          'entry-salary': '$44,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'NO',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'YES',
          stress: 'YES',
        },
        salaryChart: {
          senior: 121000,
          mid: 64000,
          entry: 44000,
        },
      },
      'Sonoma State University': {
        tableOne: {
          officer: 'Dr. Wm. Gregory Sawyer',
          location: 'Rohnert Park, CA',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '135',
          'part-time': '81',
          female: 'YES',
          minority: 'YES',
          lgbt: 'YES',
          disability: 'N/R',
          'senior-salary': '$118,000',
          'mid-salary': '$86,000',
          'entry-salary': '$62,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 118000,
          mid: 86000,
          entry: 62000,
        },
      },
      'California State University-Channel Islands': {
        tableOne: {
          officer: 'Dr. Richard Yao',
          location: 'Camarillo, CA',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '93',
          'part-time': '2',
          female: 'YES',
          minority: 'N/R',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': '$106,000',
          'mid-salary': '$71,000',
          'entry-salary': '$60,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 106000,
          mid: 71000,
          entry: 60000,
        },
      },
      'Saint Louis University': {
        tableOne: {
          officer: 'Dr. Kent Porterfield',
          location: 'St. Louis, MO',
          level: '4-year',
          control: 'private',
        },
        tableTwo: {
          'full-time': '152',
          'part-time': '30',
          female: 'YES',
          minority: 'NO',
          lgbt: 'N/R',
          disability: 'YES',
          'senior-salary': '$140,000',
          'mid-salary': '$70,000',
          'entry-salary': '$40,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'NO',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'YES',
          stress: 'YES',
        },
        salaryChart: {
          senior: 140000,
          mid: 70000,
          entry: 40000,
        },
      },
      'Lehigh University': {
        tableOne: {
          officer: 'Dr. Ricardo Hall',
          location: 'Bethlehem, PA',
          level: '4-year',
          control: 'private',
        },
        tableTwo: {
          'full-time': '74',
          'part-time': '1',
          female: 'YES',
          minority: 'NO',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': '$111,000',
          'mid-salary': '$79,000',
          'entry-salary': '$49,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 111000,
          mid: 79000,
          entry: 49000,
        },
      },
      'California Polytechnic State U.-San Luis Obispo': {
        tableOne: {
          officer: 'Dr. Keith Humphrey',
          location: 'San Luis Obispo, CA',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '460',
          'part-time': '89',
          female: 'YES',
          minority: 'N/R',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': '$178,000',
          'mid-salary': '$77,000',
          'entry-salary': '$55,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'NO',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 178000,
          mid: 77000,
          entry: 55000,
        },
      },
      'Case Western Reserve University': {
        tableOne: {
          officer: 'Louis W. Stark',
          location: 'Cleveland, OH',
          level: '4-year',
          control: 'private',
        },
        tableTwo: {
          'full-time': '160',
          'part-time': '4',
          female: 'N/R',
          minority: 'N/R',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': 'N/R',
          'mid-salary': 'N/R',
          'entry-salary': 'N/R',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 'N/R',
          mid: 'N/R',
          entry: 'N/R',
        },
      },
      'Texas A&M University-San Antonio': {
        tableOne: {
          officer: 'Dr. Melissa Mahan',
          location: 'San Antonio, TX',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '48',
          'part-time': '3',
          female: 'YES',
          minority: 'YES',
          lgbt: 'YES',
          disability: 'N/R',
          'senior-salary': '$75,000',
          'mid-salary': '$51,000',
          'entry-salary': '$42,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'NO',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'NO',
        },
        salaryChart: {
          senior: 75000,
          mid: 51000,
          entry: 42000,
        },
      },
      'The Ohio State University-Columbus': {
        tableOne: {
          officer: 'Dr. Melissa Shivers',
          location: 'Columbus, OH',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '1135',
          'part-time': '5254',
          female: 'NO',
          minority: 'YES',
          lgbt: 'N/R',
          disability: 'N/R',
          'senior-salary': '$13,000',
          'mid-salary': '$73,000',
          'entry-salary': '$48,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'NO',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 13000,
          mid: 73000,
          entry: 48000,
        },
      },
      'University of Maryland-Baltimore': {
        tableOne: {
          officer: 'Dr. Patty Alvarez',
          location: 'Baltimore, MD',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '54',
          'part-time': '173',
          female: 'YES',
          minority: 'YES',
          lgbt: 'YES',
          disability: 'NO',
          'senior-salary': '$92,000',
          'mid-salary': '$71,000',
          'entry-salary': '$57,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'NO',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'YES',
          stress: 'YES',
        },
        salaryChart: {
          senior: 92000,
          mid: 71000,
          entry: 57000,
        },
      },
      'West Chester University of Pennsylvania': {
        tableOne: {
          officer: 'Dr. Zebulun Davenport',
          location: 'West Chester, PA',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '149',
          'part-time': '28',
          female: 'YES',
          minority: 'NO',
          lgbt: 'NO',
          disability: 'NO',
          'senior-salary': '$106,000',
          'mid-salary': '$69,000',
          'entry-salary': '$47,000',
        },
        tableThree: {
          'caregiving-leave': 'NO',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 106000,
          mid: 69000,
          entry: 47000,
        },
      },
      'Virgina Tech': {
        tableOne: {
          officer: 'Dr. Frank Shushok',
          location: 'Blacksburg, VA',
          level: '4-year',
          control: 'public',
        },
        tableTwo: {
          'full-time': '831',
          'part-time': '2983',
          female: 'YES',
          minority: 'NO',
          lgbt: 'N/R',
          disability: 'NO',
          'senior-salary': '$136,000',
          'mid-salary': '$58,000',
          'entry-salary': '$45,000',
        },
        tableThree: {
          'caregiving-leave': 'YES',
          childcare: 'YES',
          'continuing-ed': 'YES',
          'ed-leave': 'YES',
          'elder-care': 'YES',
          flexible: 'YES',
          mentoring: 'NO',
          stress: 'YES',
        },
        salaryChart: {
          senior: 136000,
          mid: 58000,
          entry: 45000,
        },
      },
    },
  },
  // Put years before 2020 here.
};
